import * as THREE from 'three';
import { images } from '.';

export const defaultConfig = {
    textures: [],
    cssObjects: [],
    meshes: [],
    meshArray: [],
    images: images,
    mouse: new THREE.Vector2(),
    raycaster: new THREE.Raycaster(),
    pointer: new THREE.Vector2(),
    pointerPrev: new THREE.Vector2(),
    targetPosition: new THREE.Vector3(0, 0, 0),
    clock: new THREE.Clock(),
    time: 0,
    baseMeshSpacing: 2.2,
    width: window.innerWidth,
    height: window.innerHeight,
    PARTICLE_LAYER: 0,
    SPHERE_LAYER: 1,
    PLANE_LAYER: 2,
    slider_mesh: 3,
    aspect: window.innerWidth / window.innerHeight,
    movementSensitivity: 60,
    defaultCameraZ: 10.5,
    friction: 0.95,
    startX: 0,
    isDragging: false,
    currentPosition: 0,
    dragDelta: 0,
    lastX: 0,
    scaleFactor: 1,
    dragSpeed: 0,
    velocity: 0,
    initialDistanceScale: 0,
    slideHeight: 3.2,
    slideWidth: 1.8,
    scaleFactor_cards: 1,
    meshSpacing: 2.3,
    frustumSize: 1,
    maxDistanceScale: 0.7,
    velocityScale: 0.20,
    largePlane: null,
    isLoading: true,
    isDivOpen: false,
    isProjectsOpen: false,
    isAnimating: false,
    largeShaderMaterial: null,
    moonShaderMaterial: null,
};